### ISSUE TITLE
MITK Symbol all over 3D Screenshot

### ISSUE THREAD

**Issue by jonasboh** [MITK/MITK#281]
Dear MITK Team,

I am using MITK v. 2023-11-13 on Mac OS 13.6.6 (Ventura).
When I want to use the Screenshot Maker inside MITK I get MITK Symbols all over the Screenshot. 
Would it be possible to only have the MITK Symbol on the lower left corner like it is in the 3D View?

Thanks.
![3D_View3](https://github.com/MITK/MITK/assets/16516426/87d99fda-a0ae-4026-93a3-783aeee890ad)

**Comment by kislinsk** [comment]
First things first: It's a (known) bug. I may find time to fix it for the upcoming release. There are two workarounds available:

1. Set the Upsampling value in the Screenshot Maker to 1. This will make a 1:1 verbatim screenshot of the 3-d window. You may want to maximize the window first for a better resolution. That's it, you're done.

2. Only if you want/need upscaling nevertheless, you can get completely rid of the logo but it's tricky:

    1. Close the Workbench    

    2. Open the **prefs.xml** file where all the preferences are stored
        - Linux: ~/.local/share/DKFZ/MITK Workbench_\<n>/data/3/prefs.xml
        - Windows: %APPDATA%/../Local/DKFZ/MITK Workbench_\<n>/data/3/prefs.xml).
        - macOS: Probably something similar to Linux?

        Be aware, though, that there are probably quite a few MITK Workbench folders if you used multiple versions of MITK. You can delete all folders to reset everything. The prefs.xml file will **only be present after a first clean application exit**.

    3. Then, add `<property name="DepartmentLogo" value=""/>` to all the `org.mitk.editors.stdmultiwidget` preferences.
    
    4. Start the Workbench, et voila, easy peasy... :grimacing:

**Comment by kislinsk** [comment]
Update: I was able to fix the issue and it will be included in the upcoming MITK v2024.06 release.
