### ISSUE TITLE
Error while building MITK with VS 2022

### ISSUE THREAD

**Issue by Ria95** [MITK/MITK#283]
I am getting build error in MITK configure as 
  `Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	MSB8066	Custom build for 'H:\MITK\Bin\CMakeFiles\6f949702e7b87643bea97891955e1cfb\MITK-Configure-configure.rule;H:\MITK\Bin\CMakeFiles\6f949702e7b87643bea97891955e1cfb\MITK-Configure-build.rule;H:\MITK\Bin\CMakeFiles\6f949702e7b87643bea97891955e1cfb\MITK-Configure-install.rule;H:\MITK\Bin\CMakeFiles\28a2d4d74b202db416af7ae95b659f14\MITK-Configure-complete.rule;H:\MITK\Bin\CMakeFiles\b1a380c3e87d2c0a776c509c3ddfe99d\MITK-Configure.rule' exited with code 1.	MITK-Configure	C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets	254		
`
My Qt version is Qt6.7, i am using VTK 9.3.0 and ITK 5.3 as external modules. Compiler is VS2022

**Comment by kislinsk** [comment]
Hi, this is just a wrapper error for a CMake error. Double click on this error in Visual Studio and the cursor in the Output window should jump to the according output. There you should find the actual error message shortly before.

**Comment by Ria95** [comment]
Yes , according to the error message it is taking me to  "Microsoft.CppCommon.targets" file where it shows the custom build section " <CustomBuild Condition ="'@(_CustomBuild)' != ''"
   Sources                     ="@(_CustomBuild)"
   BuildSuffix                 ="$(_BuildSuffix)"

   MinimalRebuildFromTracking  ="false"
   AcceptableNonZeroExitCodes  ="%(_CustomBuild.AcceptableNonZeroExitCodes)"
   StdOutEncoding = "%(_CustomBuild.StdOutEncoding)"
   StdErrEncoding = "%(_CustomBuild.StdErrEncoding)"
 >
 </CustomBuild>"

**Comment by kislinsk** [comment]
I see. Providing an externally built ITK is done by setting `EXTERNAL_ITK_DIR` in the MITK superbuild. I would advise to go with the ITK that is built by the superbuild but I guess you have a good reason to provide your own ITK build. All I can say is that you should probably have a look at MITK's CMakeExternals/ITK.cmake, which basically contains all of our build settings for ITK, to see if there's a substantial difference to your build.

**Comment by Ria95** [comment]
Thank you for replying. I used MITKs ITK and the build was success, however I would like to know that if the MITK 2023.12 supports ITK 5.3 and VTK 9.3

**Comment by kislinsk** [comment]
You find this information in the according files in the CMakeExternals directory, too: https://github.com/MITK/MITK/tree/v2023.12/CMakeExternals

In MITK v2023.12, we use a patched version of ITK v5.3 and regular VTK v9.2.6.

**Comment by Ria95** [comment]
Thank you
