### ISSUE TITLE
Cmake configuration success but Build error in MITK latest source code

### ISSUE THREAD

**Issue by Ria95** [MITK/MITK#284]
Hello, I tried to build the MITK2013.12 source code, but it asked Qt 5.12, I need to build MITK on QT6.7.1 so i downloaded the latest Github code of MITK, in that Qt6 is supporting.
However i tried to Build this using Custom Build with VS 2022 x64.The ALLBUILD in debug mode is completed but the INSTALL building gives error as  some lib not found in release folder error. i tried so many times by cleaning and rebuilding , changed the directory, didnt used external ITK or VTK , still same error: This is my cmake configuration. Do i need to add or remove any modules?

My specifications are:
Visual Studio version  : Microsoft Visual Studio 2022 Community Edition (x64)
OS - windows  :10
Qt version      : 6.7.1 (evaluation version)

I am attaching the cmake config for reference:
![image](https://github.com/MITK/MITK/assets/129499586/fe610523-cab6-40c3-ba3f-e729dca4a721)
![image](https://github.com/MITK/MITK/assets/129499586/5a0e9586-f990-4a08-828b-1aa32911dad0)
![image](https://github.com/MITK/MITK/assets/129499586/1cb42f12-92f8-4483-ba7b-280a3590917c)
![image](https://github.com/MITK/MITK/assets/129499586/4a39c275-4586-44c4-8ecf-a3180a4b4ed5)
![image](https://github.com/MITK/MITK/assets/129499586/0cf8dd60-0ff2-417a-9f5d-164a0f88e42f)

**Comment by kislinsk** [comment]
Hi, installing and packaging [only works in Release configuration](https://docs.mitk.org/nightly/DeploymentPage.html).

As a side note, are you sure you want to build INSTALL instead of PACKAGE, since the latter gives you a quite a lot more flexibility by generating a redistributable ZIP archive?

**Comment by Ria95** [comment]
Oh thank you, I will build PACKAGE then, however i have my doubts.

I am trying to build an application on QT using MITK so whille developing the application i need to execute in Debug mode and for final deployment i can use Release mode .   since the libraries for debug and release will be different in MITK, if i install PACKAGE can i run my application in Debug mode of QT? 
Instead of setting MITK_BUILD_CONFIGURATION as Custom do i need to modify to other type?

**Comment by kislinsk** [comment]
Usually you build both Debug and Release and you run and debug the build tree from within Visual Studio. When you are done you PACKAGE in Release configuration.
