### ISSUE TITLE
Error while Building MITK 

### ISSUE THREAD

**Issue by Ria95** [MITK/MITK#285]
I am getting error while building MITK (GitHub latest version)  with VS2022 in debug mode, and I am getting the following error:

`Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	MSB8066	Custom build for 'H:\MITK\Bin\CMakeFiles\8ff9ce20ede95ca3088bd58589217e61\MITK-build.rule' exited with code 1.	MITK-build	C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets	254		
`

in the output iam getting error like this:
```
CMake Error at CMake/mitkFunctionCreatePlugin.cmake:79 (message):
18>  org_mitk_gui_qt_application is missing requirements and won't be built.
18>  Missing: MitkQtWidgetsExt
18>Call Stack (most recent call first):
18>  Plugins/org.mitk.gui.qt.application/CMakeLists.txt:3 (mitk_create_plugin)
18>
18>
18>CMake Error at CMake/mitkFunctionCreatePlugin.cmake:79 (message):
18>  org_mitk_gui_qt_ext is missing requirements and won't be built.  Missing:
18>  MitkQtWidgetsExt
18>Call Stack (most recent call first):
18>  Plugins/org.mitk.gui.qt.ext/CMakeLists.txt:10 (mitk_create_plugin)
18>
18>
18>-- Creating CTK plugin org_mitk_gui_qt_extapplication
18>-- Creating CTK plugin org_mitk_gui_qt_common
18>-- Creating CTK plugin org_mitk_gui_qt_stdmultiwidgeteditor
18>CMake Error at CMake/mitkFunctionCreatePlugin.cmake:79 (message):
18>  org_mitk_gui_qt_datamanager is missing requirements and won't be built.
18>  Missing: MitkQtWidgetsExt
18>Call Stack (most recent call first):
18>  Plugins/org.mitk.gui.qt.datamanager/CMakeLists.txt:3 (mitk_create_plugin)
18>
18>
18>CMake Error at CMake/mitkFunctionCreatePlugin.cmake:79 (message):
18>  org_mitk_gui_qt_properties is missing requirements and won't be built.
18>  Missing: MitkQtWidgetsExt
18>Call Stack (most recent call first):
18>  Plugins/org.mitk.gui.qt.properties/CMakeLists.txt:3 (mitk_create_plugin)
18>
18>
18>CMake Error at CMake/mitkFunctionCreatePlugin.cmake:79 (message):
18>  org_mitk_gui_qt_imagenavigator is missing requirements and won't be built.
18>  Missing: MitkQtWidgetsExt
18>Call Stack (most recent call first):
18>  Plugins/org.mitk.gui.qt.imagenavigator/CMakeLists.txt:5 (mitk_create_plugin)
18>
18>
18>-- Creating CTK plugin org_mitk_gui_qt_pixelvalue
18>
```

**Comment by kislinsk** [comment]
I believe if you scroll down you see in the summary all modules listed and why they are missing. Usually they are only disabled if they also have missing dependencies. On module level this is typically one of the third-party dependencies that are supposed to be built in the MITK superbuild.

A typical scenario for that situation is that a certain third-party dependency wasn't build in the corresponding configuration (Debug/Release) and when you switch the configuration later in the VS solution of MITK itself, it cannot be found.

In your case you are trying to build in debug, right? Open the MITK superbuild solution again, make sure to select the Debug configuration, and then build the MITK-Configure project.

In general, the recommended and usually worry-free approach is to simply do a batch build of ALL_BUILD of both Release and Debug configurations in the MITK superbuild solution. This will basically build everything in both configurations.
