### ISSUE TITLE
source code of matchpoint algorithm?

### ISSUE THREAD

**Issue by Sere1nz** [MITK/MITK#287]
Hi, where could I get the source code of matchpoint algorithm(like rigidicp)? 
Also, if I want to add other custom matchpoint algorithm, what is the procedure to import it?(if I have the cpp code of coherent point drift algorithm, what is the algorithm template and what should I do to import it?) Thank you!

**Comment by Sere1nz** [comment]
only find dll file in bin folder

**Comment by rfloca** [comment]
Hi, thank you for your question and the interest in MITK/MatchPoint. If you want to add you own algorithm in an MITK base application, the easiest way to do it is to shown in module MatchPointRegistration

You can do the same in your own module.

In MatchPointRegistration you can find two directories:

- algorithms: It contain the MatchPoint algorithm classes that should be ultimatly deployed and there profile information (the one you e.g. see in the MatchPoint browser). Here you have the full range of possibilities (from just typenaming and specifying template classes (like in mitkMultiModalRigidHeadNeckRegistrationAlgorithm.h) to complete new classes derived from the MatchPoint algorithm base clases (like mitkMultiModalTransDefaultRegistrationAlgorithm.h)
- deployment: here you decide which classes (and with which templating (e.g. pixel type or dimension) should be compiled into shared objectes. It is always the same pattern and you can see it in the cpps. The lifting is done by mapDeployAlgorithmMacro if one provides a class.
- The last thing that is needed is to generate a cmake target for that. You can see that in depoyment/CMakeLists.txt (using mitkFunctionCreateMatchPointDeployedAlgorithm; see its documentation in CMake/mitkFunctionCreateMatchPointDeployedAlgorithm.cmake).

I hope that information will help you.

**Comment by rfloca** [comment]
The MatchPoint source code is an external project. It can be found in your build tree under ep\src\MatchPoint.
It is pulled from https://github.com/MIC-DKFZ/MatchPoint.git.
But you don't need to change that repo to implement new algorithms. You can do that directly in a using project (like in an MITK module).
