### ISSUE TITLE
Why not introduce the nodes of parent-child relationship

### ISSUE THREAD

**Issue by BigBrotherHui** [MITK/MITK#295]
Why not introduce the parent-child nodes similar to those in 3D Slicer in the transformation relationship of Mitk? I've asked many friends who do development with Mitk, and they are all looking forward to this feature.Best Wishes!

**Comment by kislinsk** [comment]
Thank you for your suggestion! Could you please elaborate a bit more on how you'd like the parent-child node relationships to work within MITK's transformations? It would help us better understand your proposal and evaluate how it aligns with our current framework. Looking forward to your insights!

**Comment by BigBrotherHui** [comment]
> Thank you for your suggestion! Could you please elaborate a bit more on how you'd like the parent-child node relationships to work within MITK's transformations? It would help us better understand your proposal and evaluate how it aligns with our current framework. Looking forward to your insights!


Thank you for your reply! This mainly lies in the aspect of transformation matrices. Sometimes I hope that one object can remain relatively stationary or maintain a fixed offset with respect to another object. If the concept of parent-child nodes is introduced, then I only need to set the reference node (parent node) and then set the reference matrix (MatrixToParent). Additionally, I can query my parent nodes and child nodes, that is, which nodes refer to me and which nodes I refer to. Currently, I need to monitor Geometry to achieve a similar effect and encapsulate the logic by myself.

**Comment by kislinsk** [comment]
I see. I really understand your motivation for this feature but unfortunately it probably won't happen from our side/in the MITK codebase for several reasons.

For example, the 1:n parent-child relationship you see in the Data Manager is only half of the truth. Nodes can also have multiple parents as the concept originates from a source/derived relationship regarding data processing. Furthermore, in the vast majority of cases in medical image processing we really have to be careful to keep and "obey" physical coordinates specified by images and other data. This is why there isn't a straight forward native way of moving things around in the MITK Workbench other than image registration where it is inevitable. Think of it like a deliberate design choice as self-harm protection for the unwary user. :)

In your case I would indeed suggest to write code to easily set up and manage geometry listeners/observers (native support via itk::Object base class) for achieving hierarchical transformations. In case you have a View, override the NodeAdded/Removed methods to manage adding/removing observers as needed or also listen to Delete events of affected nodes.

**Comment by BigBrotherHui** [comment]
I also would like to ask why measurement is not allowed in three - dimensions? Sometimes I just want to measure some mesh data or for other purposes. Anyway, this function is also supported in 3D Slicer. I want to ask why annotation(pointset module) can be done in three - dimensions, but the default measurement can only interaction in two - dimensions. I know the final results can be displayed in three - dimensions,but I am referring to is the interaction.Best Wishes!
